Ca 91 password reset endpoints
metlapp/metl-api pull request #11
Opened 2020-11-06 22:00 UTC by JaycobDuffel

2020-11-06 22:34 UTC, katiemcgoff commented on .vscode/settings.json
> +}
This file shouldn't be included

2020-11-06 22:40 UTC, katiemcgoff commented on api/urls.py
There are some unused includes here.

2020-11-06 22:41 UTC, katiemcgoff commented on api/models/user.py
There are some unused includes here.

2020-11-06 22:43 UTC, katiemcgoff commented on tests/api/helpers.py
> +
No need to do the exceptions here, we are using Django 3.x and Python 3 and aren't going backward.

2020-11-06 22:46 UTC, katiemcgoff commented on tests/api/test_password_reset.py
> +
Some unused imports here.

2020-11-06 22:47 UTC, katiemcgoff commented on tests/api/test_password_reset.py
> +
Great work on these tests!

2020-11-06 22:48 UTC, katiemcgoff requested changes
some minor changes requested

2020-11-09 18:37 UTC, katiemcgoff approved these changes

2020-11-09 18:45 UTC, DawsonDease approved these changes

2020-11-09 19:08 UTC, merged