Ca 107 content endpoints
metlapp/metl-api pull request #12
Opened 2020-11-09 20:22 UTC by DawsonDease

2020-11-10 17:17 UTC, katiemcgoff commented on api/serializers/category.py
> +        fields = ["id", "name", "users", "content", "organization"]
I'm not sure we need to include content in categories, since we'd never post or patch to the category endpoint to change the content. If you want it to display only, you can add a "readonly" attribute to the field so that it only shows in the GET endpoints but is not required for the POST/PUT.

https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields

2020-11-10 17:18 UTC, katiemcgoff commented on api/serializers/content.py
> +    def __str__(self):
I don't believe a serializer needs/uses a __str__() function, that would only be in the model.

2020-11-10 17:24 UTC, katiemcgoff commented on api/models/content.py
> +    TYPES_OF_CONTENT = ((Article, "Article"), (Video, "Video"))
Great use of constants and tuples here.

2020-11-10 17:41 UTC, katiemcgoff commented on api/models/content.py
> +    Video = "Vid"
Let's uppercase these constants per standard, so ARTICLE="Article" and VIDEO="Video"

2020-11-10 17:57 UTC, katiemcgoff commented on api/views/content.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Do we need this post function? Is it doing anything special? If not we can default to the standard.

2020-11-10 23:02 UTC, katiemcgoff commented on tests/api/test_content.py
> +
Great test coverage!

2020-11-10 23:05 UTC, katiemcgoff requested changes
Some changes requested. 

Also, when everything else is complete, you should replace all the migrations with a single migration. You can do that by deleting the existing migrations, rebuilding the db, then creating a single new migration with makemigration. 

Also the migrations should go in sequence order so the new one should be 0004, to follow the already-existing 0003_category.

2020-11-12 01:38 UTC, katiemcgoff commented on api/serializers/organization.py
> +        fields = ["id", "name", "users", "content", "categories"]
Same comment as above - do we need this in the serializer?

2020-11-12 18:10 UTC, JaycobDuffel approved these changes

2020-11-12 18:15 UTC, katiemcgoff approved these changes

2020-11-12 18:17 UTC, merged