Ca 94 question and answer endpoints
metlapp/metl-api pull request #16
Opened 2020-11-16 21:37 UTC by DawsonDease

2020-11-17 18:44 UTC, katiemcgoff commented on api/migrations/0005_answer_question.py
> +        ('api', '0004_content'),
now that Schedules are merged you'll probably need to bump your migration number but that's it.

2020-11-17 18:49 UTC, katiemcgoff commented on setup.cfg
> +ignore= W293
yep

2020-11-17 18:52 UTC, katiemcgoff requested changes
Migrations need to be sorted out (can't re-number existing migrations), otherwise approved.

2020-11-17 23:46 UTC, katiemcgoff commented on api/migrations/0005_schedules.py
>      ]
In this file, since there are no actual functional changes by you - just formatting - don't check it in. We don't want formatting-only changes to make it into commits, only functional.

2020-11-18 19:17 UTC, JaycobDuffel approved these changes

2020-11-19 20:56 UTC, katiemcgoff approved these changes

2020-11-19 21:14 UTC, merged