Ca 145 membership list
metlapp/metl-api pull request #23
Opened 2020-11-25 21:07 UTC by DawsonDease

2020-11-26 00:59 UTC, katiemcgoff commented on api/models/member.py
> +    schedule = models.ManyToManyField("Schedule", related_name="member", blank=True)
This should be called "schedules" (plural) I believe. And similarly, the related name for schedules and categories should also be "members" (plural) because when we're dealing with a schedule/category, we would use this to look at it's members, not a single member.

2020-11-26 15:03 UTC, katiemcgoff commented on api/urls.py
> +    path("members/<int:pk>", member.MemberRUDView.as_view(), name="Member-actions"),
Our convention is to end all urls with a slash. Also need to fix a few other URL above, they slipped through the cracks.

2020-11-26 15:07 UTC, katiemcgoff requested changes
How about making this a sub-endpoint of the organization endpoint? Like this:
/organization/1/members/ (list, post) and /organization/1/members/5/ (get/patch/etc). 

I think that servers our needs more realistically - we won't ever want to list a complete list of members without filtering on org.

See user feed urls and views for example.

2020-11-26 18:37 UTC, JaycobDuffel approved these changes

2020-11-27 22:29 UTC, katiemcgoff approved these changes

2020-11-27 22:31 UTC, merged