Ca 152 fixed text
metlapp/metl-api pull request #25
Opened 2020-12-03 20:27 UTC by JaycobDuffel

2020-12-03 21:21 UTC, DawsonDease approved these changes

2020-12-03 22:28 UTC, katiemcgoff commented on api/views/static.py
> +
We also need the permissions class (see other endpoints) for both these views, to restrict to the admin user.

2020-12-03 22:31 UTC, katiemcgoff commented on api/models/static.py
> +        return self.name
there is no name field, so this should be something else - title probably.

2020-12-03 22:39 UTC, katiemcgoff requested changes
We also need api tests, so in the tests/api folder.

Otherwise very good, looks right and you checked all the boxes re. BaseItem.

2020-12-04 00:32 UTC, katiemcgoff commented
Another test you should probably add to is the test_get_content() test in the UserFeed api test. It confirms that the UserFeed serializer changes work.

2020-12-05 00:07 UTC, katiemcgoff approved these changes

2020-12-05 06:14 UTC, merged