Ready for PR
metlapp/metl-api pull request #28
Opened 2020-12-04 22:58 UTC by DawsonDease

2020-12-04 23:23 UTC, JaycobDuffel approved these changes

2020-12-05 01:15 UTC, katiemcgoff commented on api/models/click.py
> +    question = models.ForeignKey("Question", related_name="click", null=True, on_delete=models.SET_NULL)
We could probably make this the generic BaseItem rather than several specific models we'll have to add to later.

2020-12-05 01:17 UTC, katiemcgoff commented on api/models/click.py
> +    date = models.DateTimeField(auto_now_add=True, blank=True)
We shouldn't let this be blank, there's no use case for that.

2020-12-05 01:26 UTC, katiemcgoff commented on api/views/click.py
> +    permission_classes = [IsAdminUser]
Got permission_classes here twice.

2020-12-07 23:33 UTC, katiemcgoff commented on api/models/click.py
> +    content = models.ForeignKey(BaseItem, on_delete=models.CASCADE)
This foreign key should have related name and the delete should set to null, rather than cascade.

2020-12-07 23:34 UTC, katiemcgoff commented on api/models/click.py
> +    user = models.ForeignKey("User", related_name="click", null=True, on_delete=models.SET_NULL)
The related name for this should probably be "clicks" because one user could have many clicks.

2020-12-07 23:59 UTC, katiemcgoff requested changes
two changes requested in model

2020-12-09 00:25 UTC, katiemcgoff approved these changes

2020-12-09 18:12 UTC, merged