Ca 18 schedule notifications
metlapp/metl-api pull request #29
Opened 2020-12-10 17:57 UTC by JaycobDuffel

2020-12-10 19:52 UTC, katiemcgoff commented on api/management/commands/check_for_notifications.py
> +                    UserFeed.objects.filter(user=user, schedule=schedule).order_by('notification_date_time').all()
I'm wondering if we really need to loop through schedules - I think we could just loop through the user's whole feed, regardless of schedule. We could also probably filter out notifications that are already sent, using your new field, which would yield a significantly smaller list.

2020-12-10 21:24 UTC, katiemcgoff commented on api/settings.py
> +    ("5 * * * *", "api.cron.cron_check_for_notifications", ">> /tmp/cron_check_for_notifications_output.log"),
This timing I believe is actually every hour on the 5-minute, ie: 1:05, 2:05, etc. I'm guessing you were going for every 5 minutes, which would be ("*/5 * * * *"). 

This is a fun tool to experiment with: https://crontab.guru/

2020-12-10 21:32 UTC, katiemcgoff commented on tests/commands/test_check_for_notifications.py
> +        self.assertEqual(user_feed.first().notification_sent, False)
I'd say an additional test for this file should be that after the notification command runs, that any items in the feed that are in the future have not been notified. I believe the feed currently generates 1 day in the future (it's in settings.py somewhere) but you could change that to two in your test (by inporting settings.py and then changing it to like, 5 or something) to give yourself more wiggle room.

Alternately to that, you could include contents in your user_feed table in your fixture, and then you won't have to call the create_feed command in any of these tests, and you can add data to the table that supports specific tests.

2020-12-10 21:34 UTC, katiemcgoff commented on tests/commands/test_check_for_notifications.py
> +        self.assertEqual(user_feed.first().notification_sent, False)
ps - I'm not 100% sure you can change a settings.py setting after the application is running. TBD.

2020-12-10 21:34 UTC, katiemcgoff requested changes
changes requested

2020-12-10 22:31 UTC, katiemcgoff commented on tests/commands/test_check_for_notifications.py
> +        """ Schedule's default start date is respected."""
These test descriptions (the comment line) need to reflect the test.

These descriptions are printed when a test fails.

2020-12-11 19:30 UTC, katiemcgoff approved these changes

2020-12-11 19:30 UTC, DawsonDease approved these changes

2020-12-11 19:33 UTC, merged