Sct 50 slack users
metlapp/metl-api pull request #61
Opened 2021-01-20 22:44 UTC by DawsonDease

2021-01-21 14:40 UTC, katiemcgoff commented on api/serializers/organization.py
> +            User.objects.create_user(email=str(org.id) + "@slack.com", organization=org)
Let's make this @metlapp.com so we don't ever accidentally email slack and we know (via email catchall logs) if we're ever emailing these users.

2021-01-21 14:46 UTC, katiemcgoff commented on api/views/event.py
> +            UserSchedule.objects.create(
The comment above this line doesn't describe the next line accurately anymore.

2021-01-21 14:48 UTC, katiemcgoff commented on api/views/event.py
> +            UserSchedule.objects.create(
Also, be sure to update the descriptive comment above (lines 28-31) about which objects are being created. Need to add UserSchedule to the list.

2021-01-21 14:55 UTC, katiemcgoff commented on tests/api/test_event.py
> +
This test is technically fine, but it's a bit fragile - if some future change is made to our tests (such as loading up a fixture) that might cause this user to have an unrelated user schedule regardless of your work, this might give a false positive. A better way to test this would be to follow the relationships and check that the Schedule has a related UserSchedule. I believe there's a Schedule.users field that will get you that info.

2021-01-21 14:58 UTC, katiemcgoff commented on tests/api/test_organization.py
> +        user = User.objects.get(email=str(response.data['id']) + "@slack.com")
This .get() will fail if the user doesn't exist, which is fine but is also a messy test (results in a runtime error and the assertion never gets to happen). A cleaner way to do this would be to use a .filter() instead, and assert that users is not none (as you have) and that the length is 1 (to ensure no multiples were somehow created).

2021-01-21 14:59 UTC, katiemcgoff requested changes
Some code cleanup requested.

2021-01-22 17:03 UTC, JaycobDuffel approved these changes

2021-01-22 17:48 UTC, katiemcgoff approved these changes

2021-01-22 17:49 UTC, merged