SCT 93 Change Answer.Date
metlapp/metl-api pull request #62
Opened 2021-01-22 19:42 UTC by DawsonDease

2021-01-23 03:21 UTC, katiemcgoff commented on api/models/answer.py
> +    date = models.DateTimeField(auto_now_add=True)
We don't want it to be called date but be a datetime. Let's rename to the field itself to datetime as well.

2021-01-23 06:24 UTC, JaycobDuffel approved these changes

2021-01-25 19:31 UTC, katiemcgoff requested changes
One final change needed re read-only field.

2021-01-25 19:31 UTC, katiemcgoff commented on api/serializers/answer.py
>          read_only_fields = ['date']
This read only field needs to be updated also.

2021-01-26 03:04 UTC, katiemcgoff approved these changes

2021-01-26 17:09 UTC, merged