Sct 98 authorize zoom in app home
metlapp/metl-api pull request #64
Opened 2021-01-26 00:06 UTC by DawsonDease

2021-01-26 14:12 UTC, katiemcgoff commented on api/views/zoom.py
> +    return 'http://{}{}'.format(request.get_host(), reverse('zoom_oauth_redirect'))
Should this be a permanent change to http? Or should this be dependent on the current request?

2021-01-26 14:14 UTC, katiemcgoff commented on api/views/zoom.py
> +    url = "slack://app?team=" + org.slack_team_id + "&id=A01HK2L6S74"
What is the relevance of the ID and should it be hardcoded? Perhaps add a comment explaining if so.

2021-01-26 14:41 UTC, JaycobDuffel approved these changes

2021-01-27 18:41 UTC, katiemcgoff commented on api/serializers/organization.py
> +                  "slack_bot_user_id", "tier", "disabled", "slack_team_id", "slack_user_list", "zoom_token"]
Do we need zoom_token in the output? I don't see it used anywhere here or in scutl.

2021-01-27 18:41 UTC, katiemcgoff requested changes
remove zoom_token from serializer unless it's being used somewhere.

2021-01-27 18:58 UTC, DawsonDease commented on api/serializers/organization.py
> +                  "slack_bot_user_id", "tier", "disabled", "slack_team_id", "slack_user_list", "zoom_token"]
we need it. I just forgot to do a pull request on the scutl side. haha

2021-01-27 21:34 UTC, katiemcgoff approved these changes

2021-01-27 21:35 UTC, merged