Sct 52 send question before meeting
metlapp/metl-api pull request #65
Opened 2021-01-26 17:51 UTC by JaycobDuffel

2021-01-26 18:04 UTC, DawsonDease requested changes

2021-01-26 18:04 UTC, DawsonDease commented on tests/model/test_question.py
> +        self.assertIn(r_question, Question.objects.all())
Need a test for when all questions are asked for an org. Should be reset :)

2021-01-26 18:07 UTC, JaycobDuffel commented on tests/model/test_question.py
> +        self.assertIn(r_question, Question.objects.all())
Nice catch!

2021-01-26 18:40 UTC, DawsonDease approved these changes

2021-01-26 20:13 UTC, katiemcgoff commented on api/jobs/send_notifications.py
> +                            raise err
If there was an error, we probably should not mark the question as asked. So this ```if err: raise err``` code should probably happen before line 43-46.

2021-01-26 20:16 UTC, katiemcgoff commented on api/jobs/send_notifications.py
> +                            choices.append(choice.choice)
IF you want a pythonic way to write this (that does exactly the same thing) you could replace the for loop with this:
```
choices = [choice.choice for choice in question.choices.all()]
```

2021-01-26 20:17 UTC, katiemcgoff commented on api/jobs/send_notifications.py
> +            notification_time = item.notification_date_time - datetime.timedelta(minutes=MINUTES_PRIOR_TO_MEETING)
Can we rename this variable question_notification_time to distinguish it from the actual event notification time?

2021-01-26 20:21 UTC, katiemcgoff commented
Looks like migration 30 got removed (probably because of the conflicting 30's) so you'll need to undo that because we can't delete migrations once they're in master.

2021-01-26 20:22 UTC, katiemcgoff commented on api/migrations/0031_auto_20210126_1846.py
> +        ),
Looks like these guys are part of the deleted migration 30 so you'll need to rebuild this migration (or just delete the date and date_time field bits).

2021-01-26 20:30 UTC, katiemcgoff commented on api/models/question.py
> +        return question_list
Really great work breaking this into its own function to keep the code clean and readable.

2021-01-26 20:34 UTC, katiemcgoff commented on api/models/question.py
> +        return question_list
FYI, IF you care about pythonic style coding, for the bragging rights, you can write the for loop in the style of a fancy list comprehension:
```
resulting_list = [<thing you do to question> for question in questions if <conditional on question>]
```

2021-01-26 20:36 UTC, katiemcgoff commented on api/settings.py
> +# Number of minutes prior to meeting start time
This comment should be more clear - number of minutes before meeting start time... to do what?

2021-01-26 20:42 UTC, katiemcgoff commented on tests/commands/test_send_question.py
> +        self.assertEquals(len(Asked.objects.all()), inital_askeds)
Since the initial list initial_askeds is length 1, and the final result after doing work also expects it to be length 1, this may not be a reliable test. If the whole thing fails to do anything with the Asked table, this test will still pass. You probably need to adjust the data a bit, either in the fixture or just in this test, to get a more reliable test scenario.

2021-01-26 20:56 UTC, katiemcgoff commented on api/urls.py
> +    path("choices/<int:pk>/", asked.AskedRUDView.as_view(), name="Choice-actions"),
Do we expect any need for the "asked" endpoint? If not it's best to not include it in the urls, serializers, views etc. Seems more like its used internally only rather than something a client app (slack) would need to post/get from.

Alternately if we do expect to use the "asked" endpoint, we need tests for it in the tests/api folder.

Similar question re. the "choices" endpoint - I don't see anything in your work re. that endpoint. And I think it's actually defined above already, so maybe this is a typo?

2021-01-26 20:59 UTC, katiemcgoff commented on tests/model/test_asked.py
> +        self.assertEquals(len(Asked.objects.all()), 1)
This isn't wrong, please don't delete it, but there's not much benefit from this test - we're really testing Django's ability to create objects, rather than anything we coded. Your tests below for the question model are the kind of test we're looking for, where we have model methods that we're validating.

2021-01-26 21:32 UTC, JaycobDuffel commented on api/urls.py
> +    path("choices/<int:pk>/", asked.AskedRUDView.as_view(), name="Choice-actions"),
Definitely dont expect to use it, added it to check to see if Askeds were being creating properly, not sure about the duplicate choices, maybe rebase error or typo!

2021-01-27 01:31 UTC, katiemcgoff commented on api/views/asked.py
> +    permission_classes = [IsAdminUser]
So it seems like we don't need these views or the serializer at all, if we're not having the endpoint. If my understanding is correct, you can delete the files (sorry, I know it sucks to remove perfectly good code you wrote).

2021-01-27 21:29 UTC, katiemcgoff approved these changes

2021-01-27 21:56 UTC, merged