SCT-97 added framework for Zoom api calls that wraps token refresh an…
metlapp/metl-api pull request #69
Opened 2021-01-28 19:38 UTC by katiemcgoff

…d auth header.

2021-01-28 21:40 UTC, DawsonDease requested changes

2021-01-28 21:40 UTC, DawsonDease commented on api/services/zoom.py
> +        print(response.content)
some leftover print statements

2021-01-28 22:12 UTC, katiemcgoff commented on api/services/zoom.py
> +        print(response.content)
good catch!

2021-01-28 22:13 UTC, katiemcgoff commented on api/services/zoom.py
> +        print(response.content)
oh shoot that's because that function shouldn't have been checked in... will remove.

2021-01-28 23:53 UTC, DawsonDease approved these changes

2021-01-29 17:22 UTC, JaycobDuffel approved these changes

2021-01-29 18:46 UTC, merged