Sct 84 dont allow scutl to be added to more channels
metlapp/metl-api pull request #70
Opened 2021-01-28 21:30 UTC by DawsonDease

2021-01-28 22:35 UTC, katiemcgoff commented on api/jobs/update_slack_data.py
> +            scutl_channels = list(dict.fromkeys(channels))
Is scutl_channels actually different than channels? I believe channels is also just a list of channel IDs.

2021-01-28 22:44 UTC, katiemcgoff requested changes
Looks like your other commits are in this branch. I'll hold off reviewing until the branch is clean.

2021-01-29 17:24 UTC, JaycobDuffel approved these changes

2021-01-29 19:32 UTC, katiemcgoff commented on tests/commands/test_update_slack_data.py
> +        self.assertEqual(channel_1_count, 1)
I'm not sure we expect to be able to get duplicate channels - this comes from the call to slack_client.users_conversations() for a particular user (our bot user) so I don't think it could have duplicates. 

If it could, I don't think the test data in MockSlackClientObj is set up to test this correctly - there is only one "ONE" channel in the list already, no duplication.

2021-01-29 19:33 UTC, katiemcgoff requested changes
One test included that I don't believe is relevant, so should be removed.

Otherwise approved, but you'll need to check your migration sequencing now due to a new migration in master.

2021-01-29 21:53 UTC, katiemcgoff approved these changes

2021-01-29 21:59 UTC, merged