Sct 23 present answers before meeting starts
metlapp/metl-api pull request #72
Opened 2021-02-01 19:46 UTC by JaycobDuffel

2021-02-02 01:48 UTC, katiemcgoff commented on api/jobs/send_notifications.py
> +                            user=user.pk,
Should this be user.pk or just user (ie: the whole object)? There's inconsistency between this and the tests.

2021-02-02 01:54 UTC, katiemcgoff commented on api/jobs/send_notifications.py
> +                            f" and {answer_count[keys[2]]} answered '{keys[2]}'."
AC for the ticket says we should display as percentage rather than count (which is a pretty straight forward change from here). Let's round to zero decimal places.

2021-02-02 02:07 UTC, katiemcgoff requested changes
Let's get a few more tests - we could use an integration test for send_choice_question(), and a perhaps a test that it gets called by the notifications service.

2021-02-02 18:04 UTC, DawsonDease approved these changes

2021-02-04 19:32 UTC, katiemcgoff approved these changes

2021-02-04 19:39 UTC, merged