Sct 88 create website registration
metlapp/metl-api pull request #73
Opened 2021-02-02 20:03 UTC by DawsonDease

2021-02-03 17:55 UTC, JaycobDuffel approved these changes

2021-02-03 17:55 UTC, JaycobDuffel commented on api/views/slack_sign_in.py
> +    REDIRECT_URI = 'http://127.0.0.1:8000/slack/oauth_redirect/'
Should the url here and on line 43 be hardcoded? Or perhaps a settings variable?

2021-02-04 15:55 UTC, katiemcgoff commented on api/views/slack_sign_in.py
> +    REDIRECT_URI = 'http://127.0.0.1:8000/slack/oauth_redirect/'
I concur. Environment variable would be best since this will differ between local dev environment, staging, and production.

2021-02-04 16:01 UTC, katiemcgoff commented on api/views/slack_sign_in.py
> +            last_name=user_name[1],
This could fail if name doesn't have two strings. You can protect against it by doing something like: 
```
last_name=user_name[1] if len(user_name) >= 2 else ''
```

2021-02-04 16:05 UTC, katiemcgoff commented on api/views/slack_sign_in.py
> +    url = "http://localhost:3000/payment"
This one needs to be an environment variable.

2021-02-04 16:15 UTC, katiemcgoff commented on api/models/user.py
> +    slack_token = models.CharField(_("slack token for user"), blank=True, null=True, max_length=400)
Let's store the user's slack user id as well. I think we'll need to enhance this later to handle users that are in multiple workspaces, so we'll need to search/key by slack_user_id rather than email address. No change needed right now other than to save that data for future use.

2021-02-04 16:16 UTC, katiemcgoff requested changes
All hardcoded URLs need to be replaced using request.get_host() and/or environment variables. Can also use request.is_secure() to know whether to use http or https.

All in all looks great. I haven't reviewed the tests yet.

2021-02-04 19:54 UTC, katiemcgoff approved these changes

2021-02-04 21:10 UTC, merged