Sct 70 billed according to number of users
metlapp/metl-api pull request #79
Opened 2021-02-11 19:24 UTC by DawsonDease

2021-02-11 19:35 UTC, katiemcgoff commented on tests/commands/test_update_slack_data.py
> +    @patch('api.services.slack.SlackUtils.get_slack_client', return_value=MockSlackClientObj)
As discussed, this test is getting removed. A good replacement test would be to call the command twice - we'd expect that there are two rows in the table for the given org.

2021-02-11 19:37 UTC, katiemcgoff requested changes
Just a few changes re. the model setup, as discussed in person:
- camel case naming (OrgUsersByDay)
- don't cascade delete
- org is a foreign key rather than 1-to-1, since we expect a record created every time the `update_slack_data` job is run

2021-02-16 16:58 UTC, katiemcgoff commented on api/serializers/organization.py
> +                  "zoom_token", "slack_channel_list", "org_users_by_day"]
I don't think we want this in the serializer. I understand that you use it when programming but functionally, this cound get to be a big list quickly (at least one record per day) and it serves no purpose in the serializer.

2021-02-16 17:01 UTC, katiemcgoff commented on tests/commands/test_update_slack_data.py
> +        self.assertNotEqual(self.org.org_users_by_day, '')
Would org.org_users_by_day ever be a blank string? I believe it's a list so it might be None or have length zero, but I can't imagine it ever being a blank string. Correct me if I'm wrong.

2021-02-16 21:09 UTC, katiemcgoff approved these changes

2021-02-17 18:20 UTC, JaycobDuffel approved these changes

2021-02-17 18:23 UTC, merged