ready for test
metlapp/metl-api pull request #84
Opened 2021-02-23 20:19 UTC by JaycobDuffel

2021-02-23 21:27 UTC, katiemcgoff commented on api/urls.py
> +    url(r'^payments/save-stripe-info/$', stripe.save_stripe_info),
I'm fairly sure we can write these URLs the same was as our other URLs:
```
path("payments/test-payment/", stripe.test_payment, name="give it a name"),
```
If these are equivalent please use the path() method rather than url().

2021-02-23 21:32 UTC, katiemcgoff commented on api/views/stripe.py
> +    data = request.data
Does this work, or do you need `request.json()` rather than `request.data`? (`request.json()` is equivalent to `json.loads(request.data)`)

2021-02-23 21:39 UTC, katiemcgoff commented on requirements.txt
> +wcwidth==0.2.5
Are all of these new includes required for the stripe stuff? Seems like a lot. When I did a `pip install dj-stripe` from master and then pip freeze'd to requirements.py, I only got three new packages.

2021-02-23 21:40 UTC, katiemcgoff requested changes
changes requested

2021-02-24 18:40 UTC, katiemcgoff approved these changes

2021-02-24 18:41 UTC, katiemcgoff commented
All the code looks good. I can run the tests successfully locally. Pending that sqlite/dj-stripe issue.

2021-02-26 17:03 UTC, DawsonDease approved these changes

2021-02-26 17:04 UTC, merged